version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './frontend:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3087:3087
  backend:
    build:
      context: ./coffee/maker
      dockerfile: Dockerfile
    volumes:
      - './coffee/maker:/app'
      # - './frontend:/frontend_dir'
      - '../coframe/client:/frontend_dir'
    environment:
      - FRONTEND_DIR=/frontend_dir/
    env_file:
      - coffee/variables.env
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

