version: '3.8'

services:
  backend:
    build:
      context: ./coffee/maker
      dockerfile: Dockerfile
    volumes:
      - './coffee/maker:/app'
      - '../coframe/client:/frontend_dir'
    environment:
      - FRONTEND_DIR=/frontend_dir/
    env_file:
      - coffee/variables.env
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

